{% set name = "mo-imports" %}
{% set version = "7.230.22310" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-imports-{{ version }}.tar.gz
  sha256: da0c4b95b0dca2555e90ca7bfa8a11f29854d27ba5a9a2f8d1d4acc0edc7661b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - mo-future ==6.230.22310
    - python >=2.7

test:
  imports:
    - mo_imports
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-imports
  summary: More Imports! - Delayed importing
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
