{% set name = "mo-imports" %}
{% set version = "3.149.20327" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-imports-{{ version }}.tar.gz
  sha256: 32e3dc720c84765224d29ed7e9d6972a369d41d756e6f26ddb5b7aa01241331d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - mo-future .147.20327
    - python >=2.7

test:
  imports:
    - mo_imports
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-imports
  summary: More Imports! - Delayed importing
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
