{% set name = "mo-imports" %}
{% set version = "7.251.22317" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-imports-{{ version }}.tar.gz
  sha256: dd933f0c8d75443dd7606eb6c8ac9de4ee2c08e9fc98b868cbb6b9167b5e826d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - mo-future ==6.230.22310
    - python >=2.7

test:
  imports:
    - mo_imports
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-imports
  summary: More Imports! - Delayed importing
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
